image: docker

variables:
  GIT_SUBMODULE_STRATEGY: recursive

services:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - git submodule init
    - git submodule update --init --recursive
      if [ -d "frontend" ] && [ -n "$(ls -A frontend)" ] && [ -d "backend" ] && [ -n "$(ls -A backend)" ]; then
        echo "Submodules frontend and backend were successfully pulled and are not empty."
      else
        echo "Failed to pull submodules frontend and/or backend, or they are empty."
        exit 1
      fi
    - echo run tests in this section

step-deploy-prod:
  stage: deploy
  only:
    - main
  script:
    - sudo apt-get install -y python3-pip
    - sudo pip3 install --upgrade setuptools
    - sudo pip3 install docker-compose
    - sudo docker image prune -f
    - docker-compose build --no-cache
    - docker-compose up -d
  environment: production
  when: manual
