"""migrate_import_path

Revision ID: ac1f762624f5
Revises: e662b2035fba
Create Date: 2024-05-12 03:44:11.549508

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ac1f762624f5"
down_revision: Union[str, None] = "e662b2035fba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "action_template", sa.Column("import_path", sa.String(), nullable=True)
    )
    op.add_column(
        "action_template", sa.Column("import_func", sa.String(), nullable=True)
    )
    op.drop_column("active_action", "import_func")
    op.drop_column("active_action", "import_path")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "active_action",
        sa.Column("import_path", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "active_action",
        sa.Column("import_func", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("action_template", "import_func")
    op.drop_column("action_template", "import_path")
    # ### end Alembic commands ###
