"""add_description

Revision ID: ac7e5c319c31
Revises: ac1f762624f5
Create Date: 2024-05-12 16:30:28.802878

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ac7e5c319c31"
down_revision: Union[str, None] = "ac1f762624f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "action_template", sa.Column("description", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("action_template", "description")
    # ### end Alembic commands ###
