"""add_import_path

Revision ID: e662b2035fba
Revises: e3dd8a107bd0
Create Date: 2024-05-12 03:36:30.813854

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e662b2035fba"
down_revision: Union[str, None] = "e3dd8a107bd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("active_action", sa.Column("import_path", sa.String(), nullable=True))
    op.add_column("active_action", sa.Column("import_func", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("active_action", "import_func")
    op.drop_column("active_action", "import_path")
    # ### end Alembic commands ###
